name: myenv
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - transformers==4.37.2
    - bitsandbytes==0.41.3
    - accelerate==0.25.0
    - git+https://github.com/openai/whisper.git
    - gradio
    - gTTS